language: node_js
node_js:
  - "4.2.1"
before_script:
  - npm install -g gulp
  # - npm install
script: gulp test
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
